name: dotnet package

on: 
  push:
    branches:
    - main
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 6.0.x
      - name: Install dependencies
        run: dotnet restore tests
      - name: Build
        run: dotnet build tests --configuration Release --no-restore
      - name: Test
        run: dotnet test tests --no-restore --verbosity normal
